const BASE_URL = "/E-commerce/images";

export const imageGallery = [
  {
    id: 1,
    image: `${BASE_URL}/img-1.jpg`,
    title: "ASDF",
    price: 250.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 2,
    image: `${BASE_URL}/img-2.jpg`,
    title: "ASDF",
    price: 250.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 3,
    image: `${BASE_URL}/img-3.jpg`,
    title: "ASDF",
    price: 250.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 4,
    image: `${BASE_URL}/img-4.jpg`,
    title: "ASDF",
    price: 250.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 5,
    image: `${BASE_URL}/img-5.jpg`,
    title: "ASDF",
    price: 250.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 6,
    image: `${BASE_URL}/img-6.jpg`,
    title: "ASDF",
    price: 250.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 7,
    image: `${BASE_URL}/img-7.jpg`,
    title: "ASDF",
    price: 250.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 8,
    image: `${BASE_URL}/img-8.jpg`,
    title: "ASDF",
    price: 250.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 9,
    image: `${BASE_URL}/img-9.jpg`,
    title: "ASDF",
    price: 250.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 10,
    image: `${BASE_URL}/img-10.jpg`,
    title: "ASDF",
    price: 250.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 11,
    image: `${BASE_URL}/img-11.jpg`,
    title: "ASDF",
    price: 250.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 12,
    image: `${BASE_URL}/img-12.jpg`,
    title: "ASDF",
    price: 250.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 13,
    image: `${BASE_URL}/img-13.jpg`,
    title: "ASDF",
    price: 250.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 14,
    image: `${BASE_URL}/img-14.jpg`,
    title: "ASDF",
    price: 250.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 15,
    image: `${BASE_URL}/img-15.jpg`,
    title: "ASDF",
    price: 250.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 16,
    image: `${BASE_URL}/img-16.jpg`,
    title: "ASDF",
    price: 250.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
];

export const newArrivals = [
  {
    id: 17,
    image: `${BASE_URL}/img-17.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "Elegant sheer curtains for a light and airy feel.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 18,
    image: `${BASE_URL}/img-18.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "Bold patterned curtains to make a statement.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 19,
    image: `${BASE_URL}/img-19.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "Classic blackout curtains for complete privacy.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 20,
    image: `${BASE_URL}/img-20.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "Luxurious velvet curtains for a touch of opulence.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 21,
    image: `${BASE_URL}/img-21.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "Modern geometric print curtains for a contemporary look.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 22,
    image: `${BASE_URL}/img-22.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "Natural linen curtains for a rustic charm.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 23,
    image: `${BASE_URL}/img-23.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "Vibrant colored curtains to brighten up your space.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 24,
    image: `${BASE_URL}/img-24.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "Subtle pastel curtains for a soft, calming effect.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 25,
    image: `${BASE_URL}/img-25.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "Textured curtains for added depth and interest.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 26,
    image: `${BASE_URL}/img-26.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "Floral print curtains for a fresh, natural look.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 27,
    image: `${BASE_URL}/img-27.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "Striped curtains for a classic, timeless appeal.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
];

export const blindsImages = [
  {
    id: 28,
    image: `${BASE_URL}/img-28.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "Elegant roller blinds for a sleek finish.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 29,
    image: `${BASE_URL}/img-29.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "Stylish Venetian blinds for adjustable light control.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 30,
    image: `${BASE_URL}/img-30.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "Modern vertical blinds for a contemporary look.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 31,
    image: `${BASE_URL}/img-31.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "Classic Roman blinds for a timeless elegance.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 32,
    image: `${BASE_URL}/img-32.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "Functional blackout blinds for complete darkness.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 33,
    image: `${BASE_URL}/img-33.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "Sheer blinds for a soft, diffused light effect.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
];

export const wallpaperImages = [
  {
    id: 34,
    image: `${BASE_URL}/img-34.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 35,
    image: `${BASE_URL}/img-35.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 36,
    image: `${BASE_URL}/img-36.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 37,
    image: `${BASE_URL}/img-37.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 38,
    image: `${BASE_URL}/img-38.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 39,
    image: `${BASE_URL}/img-39.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 40,
    image: `${BASE_URL}/img-40.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 41,
    image: `${BASE_URL}/img-41.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 42,
    image: `${BASE_URL}/img-42.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 43,
    image: `${BASE_URL}/img-43.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 44,
    image: `${BASE_URL}/img-44.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 45,
    image: `${BASE_URL}/img-45.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 46,
    image: `${BASE_URL}/img-46.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 47,
    image: `${BASE_URL}/img-47.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 48,
    image: `${BASE_URL}/img-48.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 49,
    image: `${BASE_URL}/img-49.jpg`,
    title: "ASDF",
    price: 300.0,
    description: "test",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
];

export const curtainFabricsImages = [
  {
    id: 50,
    image: `${BASE_URL}/img-50.jpg`,
    title: "bold elegance",
    price: 200.0,
    description:
      "Make a statement with our bold elegance curtain fabric, featuring vibrant patterns and rich colors to elevate any room.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 51,
    image: `${BASE_URL}/img-51.jpg`,
    title: "soft serenity",
    price: 200.0,
    description:
      "Create a calming atmosphere with our soft serenity curtain fabric, designed with gentle hues and delicate textures for a peaceful retreat.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 52,
    image: `${BASE_URL}/img-52.jpg`,
    title: "modern chic",
    price: 200.0,
    description:
      "Add a touch of sophistication with our modern chic curtain fabric, featuring sleek designs and contemporary patterns perfect for stylish interiors.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 53,
    image: `${BASE_URL}/img-53.jpg`,
    title: "classic charm",
    price: 200.0,
    description:
      "Embrace timeless beauty with our classic charm curtain fabric, showcasing elegant patterns and traditional colors that never go out of style.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 54,
    image: `${BASE_URL}/img-54.jpg`,
    title: "nature's touch",
    price: 200.0,
    description:
      "Bring the outdoors in with our nature's touch curtain fabric, featuring earthy tones and organic patterns inspired by the beauty of nature.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 55,
    image: `${BASE_URL}/img-55.jpg`,
    title: "vibrant vibes",
    price: 200.0,
    description:
      "Infuse energy into your space with our vibrant vibes curtain fabric, designed with bold colors and dynamic patterns to create a lively ambiance.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 56,
    image: `${BASE_URL}/img-56.jpg`,
    title: "elegant textures",
    price: 200.0,
    description:
      "Experience luxury with our elegant textures curtain fabric, featuring rich materials and intricate designs that add depth and sophistication to any room.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 57,
    image: `${BASE_URL}/img-57.jpg`,
    title: "playful patterns",
    price: 200.0,
    description:
      "Add a fun twist to your decor with our playful patterns curtain fabric, showcasing whimsical designs and cheerful colors that brighten up any space.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 58,
    image: `${BASE_URL}/img-58.jpg`,
    title: "subtle sophistication",
    price: 200.0,
    description:
      "Achieve understated elegance with our subtle sophistication curtain fabric, featuring muted tones and refined patterns for a chic and polished look.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 59,
    image: `${BASE_URL}/img-59.jpg`,
    title: "luxury linen",
    price: 200.0,
    description:
      "Indulge in the softness of our luxury linen curtain fabric, crafted from high-quality materials that offer both comfort and style for your living spaces.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
  {
    id: 60,
    image: `${BASE_URL}/img-60.jpg`,
    title: "geometric glamour",
    price: 200.0,
    description:
      "Make a bold statement with our geometric glamour curtain fabric, featuring striking shapes and patterns that add a modern edge to any room.",
    brand: "Other",
    type: "Curtains",
    subtype: "Blackout Curtains",
    lightFiltration: "Blackout",
    otherFeatures: "Washable, Wrinkle-free",
  },
];